# Generated by Django 6.0 on 2026-01-03 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0002_chaivarity_description_chaicertificate_chaireview_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chaicertificate",
            old_name="valid_untill",
            new_name="valid_until",
        ),
        migrations.RenameField(
            model_name="chaireview",
            old_name="data_added",
            new_name="date_added",
        ),
        migrations.AlterField(
            model_name="chaireview",
            name="chai",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="chai.chaivarity",
            ),
        ),
    ]
